rustprooflabs/pgosm-flex

- README.md
- flex-config/all_tags.lua
- flex-config/all_tags.sql
- flex-config/building.lua
- flex-config/natural.lua
- flex-config/place.lua
- flex-config/road.lua
- flex-config/road_major.lua
- flex-config/run-all.lua
- flex-config/run-all.sql
- flex-config/run-no-tags.lua
- flex-config/run-no-tags.sql
- flex-config/traffic.lua
- flex-config/unitable.lua
Creating `osm.tags` table with `osm_id` along with `osm_type` and `tags`.  Remove JSON tags processing from individual feature tables.
* Quick test showed building polygon table reduced by 25% size on disk.  Assumption is most tables will see noticeable reduction in size, some more and some less.
* Removes need for each Lua script to have its own `clean_tags()` function. 
* Tags will have all values in their raw forms, including values cleaned and stored in main feature tables.  Benefit - Allows verifying values stored in feature tables against their raw form.  Can help catch issues in columns that have cleaning applied.  E.g. `maxspeed` and `height` columns often remove units defined in text and convert to OSM defaults.  
* Creates a single place to enable/disable use of JSONB tags
* …
> Isolate tags in JSONB to single table

- flex-config/all_tags.sql
Starting with adding the `osm_url` column on the `osm.tags` table.  I think adding this to every table might be helpful, need to look at costs of doing so on larger data sources first.
> Add generated column to provide link to OpenStreetMap.org

- README.md
- flex-config/place.sql
Original method worked well on small regions (e.g. Colorado).  Larger regions like U.S. suffered from long single-threaded load w/ no way to monitor progress or guesstimate completion.  New method defines procedure that loops through in variable-sized batches.  Makes it easy to cancel running without losing progress on processing.
Will work up improved usage examples in near future.
Progresses #37.
> Improve nested polygon handling

- DOCKER-BUILD.md
- docker/run_pgosm_flex.sh
Resolves #60
Improves readme, tagging Docker images w/ PgOSM-Flex version, not Pg version.  The maintained docker image will always be the latest supported Postgres/PostGIS image.
> Improve Docker processing

- QUERY.md
- flex-config/all_tags.lua
- flex-config/unitable.lua
Was looking into the impact of #2.  Found `osm.tags` and `osm.unitable` were both missing major portions of the total relations. Easy to all all to tags, less easy adding all to `unitable` due to handling geometry types.  
Example OSM IDs of relations:
* `161644`
* `62152`
* `416064`
Query to find relations missing from `unitable`.
```sql
SELECT t.*
FROM osm.tags t
WHERE t.geom_type = 'R' 
AND NOT EXISTS (
SELECT 1
FROM osm.unitable u
WHERE u.geom_type = t.geom_type AND t.osm_id = u.osm_id
);
```
> Relations missing from tags and unitable

- flex-config/helpers.lua
- flex-config/sql/building.sql
- flex-config/style/building.lua
Addresses #98 and #97.  Other improvements are being found in the process. :+1:
----
Initial testing shows this adds new building records in the DC sub-region such as this:  https://www.openstreetmap.org/way/66346595
Seems to be a good addition.  For this particular building it appears potentially `office=*` needs to be considered a building by default too.
Idea of # of records affected:
```sql
SELECT COUNT(*),
COUNT(*) FILTER (WHERE b.osm_type = 'address') AS address_record,
COUNT(*) FILTER (WHERE b.osm_type != 'address') AS building_tag_exists
FROM osm.vbuilding_all b
INNER JOIN osm.tags t ON b.osm_id = t.osm_id AND b.geom_type = t.geom_type
;
```
```bash
count |address_record|building_tag_exists|
------|--------------|-------------------|
178647|         17000|             161647|
``` …
> Improve building layer - Addresses, Offices and columns

- DOCKER-RUN.md
- Dockerfile
- MANUAL-STEPS-RUN.md
- README.md
- docker/osm2pgsql_recommendation.py
- docker/run_pgosm_flex.sh
Closes #129.
Includes a bunch of improvements throughout the README files.  Some changes RE the main topic here; also removing duplication, restructuring to better guide through Docker usage for easy get-started path.
> Update Docker process to use dynamic osm2pgsql command via API

- .github/workflows/docker-build.yml
Should make investigating/fixing #132 easier.  Pushing image tagged as `ghdev` to keep out of the way for prod systems.
> Building images on push

- .github/workflows/docker-build.yml
Using Docker Hub's builder which does not suffer from the problem in #132.  Removing the Push from GH actions to DH.
Plan to keep using GH's actions for testing as pushes coming through, will enhance that in the future.
> Stop GH actions from sending to Docker Hub

- docker/pgosm_flex.py
Closes #163.
Example of change in log file.
```bash
2021-08-30 18:06:57,204:ERROR:pgosm-flex:pgosm_flex:Missing PBF file for 2019-01-02. Cannot proceed.
```
At command line, raises `FileNotFoundError`.
```bash
FileNotFoundError: Missing PBF file for 2019-01-02. Cannot proceed.
```
> Raise error when PBF file is missing for historic date

- db/qgis-style/README.md
- flex-config/sql/road.sql
- flex-config/style/road.lua
Progresses #172.
Add comment in Lua code to clarify that nil is expected for specific values from `oneway` tag.
Improve comments in SQL to explain the expected values.
> Clarify handling of oneway tag and resulting values in Postgres. 

- README.md
- docker/pgosm_flex.py
- docs/DOCKER-RUN.md
Based on suggestions from @jacopofar in #186 ([comment](https://github.com/rustprooflabs/pgosm-flex/pull/186/files/93446a1a9731052fd9bd532ee6e3f93fba5a9125#r738348780)) to not force logs into a logfile, instead letting the user control what happens.
* Redirects log output from file to stdout
* No longer logs `osm2pgsql_command` to avoid showing password
* Update `docker exec` examples to remove unnecessary env vars passed in
> Logs go to stdout instead of internally defined logfile

- Makefile
- docker/db.py
- docker/osm2pgsql_recommendation.py
- docker/pgosm_flex.py
Closes #192.
Pulled `--input-file` feature from @jacopofar commit 2662624 from #186.  Updated for changes made in 0.4.0.
Other changes in this PR:
* Adjusted the output filename to match the existing filename pattern
* Improved handling of input filename passed to osm2pgsql recommendation
* Removed `--debug` from make commands
> Enable explicit input file

- Makefile
- docker/pgosm_flex.py
* Will resolve #197
* Addresses the Makefile portion of #199.
The fix for #197 is straightforward, sorry for the oversight!  The updates to the Makefile adds a new test for the region specific logic.
Previously had daisy-chained the build, copy, permissions, and `docker exec` commands into one big target.  This splits that logic out so each `docker-exec` is within its own target which starts by cleaning the environment, builds/runs the container, copies the file(s) needed, and runs docker-exec.
There are 3 `docker-exec-*` targets that ensure the main variations for processing work.
> Fix subregion bug, improve Makefile

- docker/pgosm_flex.py
- docs/DOCKER-RUN.md
Issue reported in #198 can't be resolved by improving the file name handling, at least not easily. The issue stems from the decision to tightly couple to Geofabrik's download server.  This PR raises an error when a slash is detected in the region name and subregion is none, in these cases the portion after the last `/` should be in the subregion.
This also updates the documentation to add a section about the region/subregion, and show this example.  I'm sure there's room for improvement in the wording, this is a quick start to improve this.
> Improve usability around region/subregion

- docker/pgosm_flex.py
Addresses part 2 of #199.  It does not unset after the run, only before a subsequent run.  This leaves the env vars available in the docker container after processing (helpful for troubleshooting) but avoids the contamination of subsequent runs.
> Unsetting env vars before setting them for current run.

- Makefile
- docker/geofabrik.py
- docker/helpers.py
- docker/pgosm_flex.py
- docker/tests/test_geofabrik.py
- docker/tests/test_pgosm_flex.py
Progresses #193.  Code cleanup and unit tests.
* Moves Geofabrik file handling code to dedicated module
* Moves date and md5 validation to new `helpers.py` (sets stage to allow validation w/ `--input-file`)
* Additional unit tests
* `make` outputs coverage report after running unit tests
> Code restructuring, cleanup, tests

- docker/db.py
- docker/pgosm_flex.py
Progresses #193.  Improve code related to Postgres connections.  No functional changes.
* Remove hard coded `localhost`. Sets stage to enable Postgres connection outside of Docker
* Remove `pg_isready` in favor of version check to establish if Postgres is available
* Move `wait_for_postgres` from `pgosm_flex.py` to `db.py`
* Time between checking for Pg available reduced from 5 seconds to 3 seconds -- should still be long enough to prevent false positives
> Cleanup and restructure Postgres connection code

- docker/db.py
- docker/geofabrik.py
- docker/helpers.py
- docker/osm2pgsql_recommendation.py
- docker/pgosm_flex.py
- docker/tests/test_db.py
- docker/tests/test_geofabrik.py
- docker/tests/test_helpers.py
- docker/tests/test_osm2pgsql_recommendation.py
Progresses #193
* Improve `helpers.verify_checksum()`, add unit tests
* Passing explicit path (`db_path`, `flex_path`) instead of full `paths` dict - Makes clearer what is used where
* Consolidate handling of Postgres connections through the `PGOSM_CONN` env var -- that var is required by the Lua scripts so made sense to standardize on that
> Cleanup Postgres connections, paths, and testing

- flex-config/sql/pgosm-meta.sql
- flex-config/style/pgosm-meta.lua
Add `osm2pgsql_mode` column to track when create/append mode was used.  Will benefit #211.
> Track osm2pgsql mode (create/append) in osm.pgosm_flex table

- Makefile
- docker/db.py
- docker/pgosm_flex.py
- docker/tests/test_pgosm_flex.py
- tests/run-output-tests.sh
* More improvements RE #193
* :warning: Change output `.sql` filename to include date - Makes pattern consistent, only affects use with `--input-file`
* Adjust Makefile to continue running coverage & data output tests even when python unit tests fail
> Continue reducing use of paths dict in favor of specific values

- Makefile
- README.md
- requirements.txt
Bump osm2pgsql-tuner version to enforce osm2pgsql's minimum RAM requirement in Docker. See https://github.com/rustprooflabs/osm2pgsql-tuner/issues/17
Add similar notes to README.
> Enforce osm2pgsql minimum RAM

- Dockerfile
This PR updates the Dockerfile installation to use a specific tag/branch of osm2pgsql install to clone specific tag/branch instead latest branch.  Linking to [osm2pgsql v1.6.0](https://github.com/openstreetmap/osm2pgsql/releases/tag/1.6.0), the current latest.
> Be specific about osm2pgsql version

- flex-config/style/infrastructure.lua
Fixed an inconsistency with `infrastructure.lua` which referenced the `aeroways` tag, but did not import any features
> include aeroway tag

- README.md
- docs/APPEND-MODE.md
- docs/MANUAL-STEPS-RUN.md
- flex-config/sql/pgosm-meta.sql
- flex-config/sql/place.sql
- requirements.txt
Progresses #211.
Add db functions to support append mode, one to run before osm2pgsql, one to run after.
Documentation written to use the `osm2pgsql-replication`, bundled with osm2pgsql.  Other methods of managing the diff data for updates should work.
> Support append mode

- flex-config/style/building.lua
This is an attempt at fixing #227 
Importing Berlin I found that 3 postal codes did appear as buildings. With this change they are gone (but maybe should also be added to the places).
> Ignore postal_code as a building

- docker/osm2pgsql_recommendation.py
- requirements.txt
Fix issue with `--input-file` and absolute paths if not using `/app/output` directory, see #229.
* Updated osm2pgsql-tuner to `0.0.5rc1` :warning: https://github.com/rustprooflabs/osm2pgsql-tuner/pull/22
Initial testing seems to fix the issue, allowing this to work.
```
docker run --name pgosm -d --rm     -v ~/pgosm-data:/customlocation     -v /etc/localtime:/etc/localtime:ro     -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD     -p 5433:5432 -d rustprooflabs/pgosm-flex
docker exec -it     pgosm python3 docker/pgosm_flex.py     --ram=8     --input-file=/customlocation/my-custom.osm.pbf 
```
> Fix absolute path with `--input-file`

- Dockerfile
- docs/MANUAL-STEPS-RUN.md
Issue with older luarocks installed by `apt install luarocks`.  Resulted in v2.4.0 (circa 2016?) installed.  Failure from still using the unsecure `git://` protocol.  Using method documented in #218 hoping it fixes the issue.
https://github.com/rustprooflabs/pgosm-flex/runs/5684687464?check_suite_focus=true
```
> [ 5/11] RUN luarocks install luasql-postgres PGSQL_INCDIR=/usr/include/postgresql/:
#9 1.124 Installing https://luarocks.org/luasql-postgres-2.6.0-1.rockspec
#9 1.438 Cloning into 'luasql'...
#9 1.545 fatal: remote error: 
#9 1.545   The unauthenticated git protocol on port 9418 is no longer supported.
#9 1.545 Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
#9 1.547 
#9 1.547 Error: Failed cloning git repository.
------ …
```
> Manual install luarocks

- flex-config/style/infrastructure.lua
- tests/expected/infrastructure_line_osm_type_subtype_count.out
- tests/expected/infrastructure_point_osm_type_subtype_count.out
- tests/expected/infrastructure_polygon_osm_type_subtype_count.out
Progresses #239.  Needs larger-scale testing after merging into dev.  My common tests in D.C. and Colorado do not include any of the `emegency=assembly_point` tags in question. 
Changes to infrastructure tables:
* Moves `osm_type`s to be under `osm_type=emergency`:   `fire_hydrant`, `emergency_phone` and `emergency_access_point`
* Catches all other `emergency` tags
* Simplify tag parsing
> Update emergency tags in infrastructure to use osm_subtype

- docker/db.py
- docs/DOCKER-RUN.md
There wasn't an ability to use non-default Postgres port.
> Add POSTGRES_PORT to conn string options

- docs/MANUAL-STEPS-RUN.md
Update manual steps to use HTTPS for git clone and to limit to `--depth 1`.
> Fix manual steps - git clone

- docs/PERFORMANCE.md
The performance notes are rather outdated at this point.
Updating performance notes for current version of PgOSM Flex, completed minimal and started default layerset.
> Update performance notes

- requirements.txt
Main change was to bump [osmium to v3.3.0](https://github.com/osmcode/pyosmium/releases/tag/v3.3.0). Other requirements were defined w/ >= and just bumped to the versions installed in the latest Docker image.
> Bump requirements versions

- Makefile
- flex-config/sql/place.sql
- flex-config/sql/public_transport.sql
- flex-config/sql/road.sql
- flex-config/sql/road_major.sql
- flex-config/sql/water.sql
- flex-config/style/public_transport.lua
- flex-config/style/road.lua
- flex-config/style/road_major.lua
- flex-config/style/water.lua
Closes https://github.com/rustprooflabs/pgosm-flex/issues/255.
My intention of this particular view isn't for it to be queried directly, but that doesn't mean someone somewhere isn't.  This is the reason for bumping version to 0.6.0 instead of continuing with 0.5.2.
* Rename backend view `places_in_relations` to `place_polygon_in_relations` https://github.com/rustprooflabs/pgosm-flex/commit/5a57c5eef03054aaafa285b0d2d6dbc878bfa1ce
New views to be preferred by default over the base table name (w/out `v` in the name).
* `osm.vroad_line`
* `osm.vroad_polygon`
* `osm.vroad_major`
* `osm.vwater_line`
* `osm.vwater_polygon`
* `osm.vpublic_transport_line`
* `osm.vpublic_transport_polygon`
The materialized views all have related views used.  Not listed here, not expected to be primary use views.
> Improve relation handling

- db/qc/osm_tag_suggestions.sql
Add missing street name check when housenumber exists. Improve QC queries to use temp table for easier follow-up queries.
> Improve Quality Control queries

- flex-config/style/amenity.lua
- flex-config/style/building.lua
- flex-config/style/indoor.lua
- flex-config/style/infrastructure.lua
- flex-config/style/landuse.lua
- flex-config/style/leisure.lua
- flex-config/style/natural.lua
- flex-config/style/place.lua
- flex-config/style/poi.lua
- flex-config/style/public_transport.lua
- flex-config/style/road.lua
- flex-config/style/road_major.lua
- flex-config/style/shop.lua
- flex-config/style/tags.lua
- flex-config/style/traffic.lua
- flex-config/style/unitable.lua
- flex-config/style/water.lua
Updating styles to take advantage of newer `insert` and `as_<geomtype>()` functions.  Other minor cleanup, removing extra spaces, etc.
> Modernize styles

- CODE_OF_CONDUCT.md
Adding Code of Conduct, based on OpenStreetMap-Carto's CoC.  https://github.com/gravitystorm/openstreetmap-carto/blob/master/CODE_OF_CONDUCT.md
> Add Code of Conduct based on OpenStreetMap Carto project.

- CODE_OF_CONDUCT.md
- Dockerfile
- flex-config/style/amenity.lua
- flex-config/style/building.lua
- flex-config/style/indoor.lua
- flex-config/style/infrastructure.lua
- flex-config/style/landuse.lua
- flex-config/style/leisure.lua
- flex-config/style/natural.lua
- flex-config/style/place.lua
- flex-config/style/poi.lua
- flex-config/style/public_transport.lua
- flex-config/style/road.lua
- flex-config/style/road_major.lua
- flex-config/style/shop.lua
- flex-config/style/tags.lua
- flex-config/style/traffic.lua
- flex-config/style/unitable.lua
- flex-config/style/water.lua
> Merge a few change sets

- docker/pgosm_flex.py
Hi there,
First of all, thanks for the awesome project. I watched your talk on PostGIS + OSM and followed it to here. This whole process makes it really easy to work with the large amounts of data OSM provides. 
I was playing around with the docker scripts and I noticed running `--append` with `--input` would lead to an error here because `pbf_filename` was unassigned. I know append is experimental, so I'm not sure if this has unintentional side-effects but I thought I would submit this PR anyway. 
I tried to run the tests Makefile as suggested but I kept getting permission denied/file not found errors for the downloaded region file. Not sure if you know what may be the issue here?
In any case, let me know if I can be of any more assistance. Cheers
> Fix using `--append` with input file

- Dockerfile
I just noticed that when I changed the Docker image for Pg15 (#260) I accidentally set this project to use PostGIS 3.4-dev instead of PostGIS 3.3.  This change pins to the 3.3 version for stability.
> Adjust Dockerfile to use PostGIS 3.3 instead of master branch that uses 3.4-dev

- Makefile
Closes #265, in response to #264.
I verified this additional test run catches the issue if I revert the change in #264.
```bash
<truncated output>
Post-processing road_major
2022-11-25 08:11:35,839:INFO:pgosm-flex:pgosm_flex:Skipping calculating nested polygons
Traceback (most recent call last):
File "/app/docker/pgosm_flex.py", line 538, in <module>
run_pgosm_flex()
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke …
```
> Add Make step to test initial --append call with --input-file

- docker/db.py
Split creation of osm schema and PostGIS extension to dedicated steps to always run.
This will allow the instructions for using external Postgres connections to be closer to using built-in connection.
> Always create osm schema and PostGIS extension

- docker/helpers.py
- docker/pgosm_flex.py
Various logging improvements.
* Improve messages related to `--append` mode
* Switching from `subprocess.run()` to `subprocess.POpen()` to provide quicker logging
> Improve logging

- docker/db.py
- docker/osm2pgsql_recommendation.py
- docker/pgosm_flex.py
- docs/DOCKER-RUN.md
Internally renaming `append` variable to `replication`. No functional changes.  This renames variables to set stage for coming changes, documents a few details, and generally makes it more clear osm2pgsql-tuner is being used, not a wrapper around `osm2pgsql --append` as it would appear.
Sets stage for changes outlined in https://github.com/rustprooflabs/pgosm-flex/issues/275#issuecomment-1340362190
> Internally rename append to replication

- flex-config/sql/amenity.sql
- flex-config/sql/building.sql
- flex-config/sql/infrastructure.sql
- flex-config/sql/landuse.sql
- flex-config/sql/leisure.sql
- flex-config/sql/natural.sql
- flex-config/sql/place.sql
- flex-config/sql/poi.sql
- flex-config/sql/public_transport.sql
- flex-config/sql/road.sql
- flex-config/sql/traffic.sql
- flex-config/sql/water.sql
- flex-config/style/amenity.lua
- flex-config/style/building.lua
- flex-config/style/indoor.lua
- flex-config/style/infrastructure.lua
- flex-config/style/landuse.lua
- flex-config/style/leisure.lua
- flex-config/style/natural.lua
- flex-config/style/place.lua
- flex-config/style/poi.lua
- flex-config/style/public_transport.lua
- flex-config/style/road.lua
- flex-config/style/road_major.lua
- flex-config/style/shop.lua
- flex-config/style/traffic.lua
- flex-config/style/water.lua
RE #276 
Moving index creation on tables to Lua styles.  Adding more indexes on columns I use frequently, using partial indexes in a few places.
> Move index creation, add more indexes

- docker/helpers.py
- docker/pgosm_flex.py
- docs/DOCKER-RUN.md
- flex-config/helpers.lua
- flex-config/style/amenity.lua
- flex-config/style/building.lua
- flex-config/style/indoor.lua
- flex-config/style/infrastructure.lua
- flex-config/style/landuse.lua
- flex-config/style/leisure.lua
- flex-config/style/natural.lua
- flex-config/style/place.lua
- flex-config/style/poi.lua
- flex-config/style/public_transport.lua
- flex-config/style/road.lua
- flex-config/style/road_major.lua
- flex-config/style/shop.lua
- flex-config/style/traffic.lua
- flex-config/style/water.lua
Follow up to #279, RE https://github.com/openstreetmap/osm2pgsql/issues/1357.  Changes to index creating also allows switching between GIST and SP-GIST indexes. 
Add `--sp-gist` to the `docker exec` command.
```bash
docker exec -it \
pgosm python3 docker/pgosm_flex.py \
--ram=8 \
--region=north-america/us \
--subregion=district-of-columbia \
--sp-gist
```
> Allow SP-GIST indexes

- README.md
- db/data-migration/0.6.3.sql
- flex-config/sql/road_major.sql
- flex-config/sql/shop.sql
- flex-config/style/road_major.lua
* Bump minimum osm2pgsql version to 1.8.0
osm2pgsql 1.8.0 is not released yet, using latest main branch from osm2pgsql makes it available now.
> Cleanup for 0.6.3 release

- Makefile
- README.md
- docker/pgosm_flex.py
Addresses #266.
:warning: The `--skip-dump` option is no longer functional after this change. :warning:
This PR updates the runtime options to use `--pg-dump` option instead of `--skip-dump`. The default operation changes from including the `pg_dump` step to excluding it.
> Change pg_dump to optional, instead of default

- docker/pgosm_flex.py
Follow up to #291 - remove options from function call.  Now passes `make`.
> Really remove options

- README.md
- docs/DOCKER-RUN.md
- docs/POSTGRES-PERMISSIONS.md
- docs/ROUTING.md
0.7.0 is bringing a number of breaking changes that result in a lot of docs that needed serious refreshing.
Note:  Some links in this description will break after deleting the associated branch. They're here to make it easier for me to navigate now.
Add quick start to main readme ([current link](https://github.com/rustprooflabs/pgosm-flex/tree/refresh-docs#quick-start)).  That's the piece I always want and can quickly modify for what I'm working on today.  It feels a bit redundant with the Docker Usage section ([current link](https://github.com/rustprooflabs/pgosm-flex/tree/refresh-docs#docker-usage)) but I think that's okay in this case.  (Open to opinions on that!)
Run section ([current link](https://github.com/rustprooflabs/pgosm-flex/blob/refresh-docs/docs/DOCKER-RUN.md#run-pgosm-flex- …
> Refresh documentation for 0.7.0 release

- docker/helpers.py
- docker/pgosm_flex.py
- docs/src/REPLICATION.md
- flex-config/sql/pgosm-meta.sql
- flex-config/style/pgosm-meta.lua
Closes #295.
Add osm2pgsql_replication column to track when osm2pgsql-replication mode is used in `osm.pgosm_flex` table.
```sql
SELECT id, region, osm_date, pgosm_flex_version,
osm2pgsql_mode, osm2pgsql_replication
FROM osm.pgosm_flex 
;
```
```
┌────┬───────────────────────────────────────┬────────────┬────────────────────┬────────────────┬───────────────────────┐
│ id │                region                 │  osm_date  │ pgosm_flex_version │ osm2pgsql_mode │ osm2pgsql_replication │
╞════╪═══════════════════════════════════════╪════════════╪════════════════════╪════════════════╪═══════════════════════╡
│  1 │ north-america/us-district-of-columbia │ 2022-12-30 │ 0.7.0-01ecd52      │ create         │ t                     │
│  2 │ north-america/us-district-of-columbia │ 2023-02-15 │ …
```
> Add `osm2pgsql_replication` column to `osm.pgosm_flex`

- docs/src/SUMMARY.md
- docs/src/common-customization.md
- docs/src/customizations.md
- docs/src/postgres-external.md
- docs/src/postgres-permissions.md
- docs/src/query.md
- docs/src/quick-start.md
- docs/src/readme.md
- docs/src/routing.md
Fixing some things broken in #305, and some things that were broken in the original change to mdbook.
> Fix broken links between pages in docs

- db/qgis-style/README.md
- docker/db.py
- docker/pgosm_flex.py
- docker/qgis_styles.py
- docker/tests/test_geofabrik.py
- docker/tests/test_pgosm_flex.py
- docs/src/SUMMARY.md
- docs/src/performance.md
- docs/src/qgis-styles.md
- docs/src/troubleshooting.md
Closes #307.
Moves the original code for QGIS layer styles into new module, splits logic into logical functions.  Add new function to update the data before loading from staging to prod.
Variety of documentation improvements.
> QGIS styles - set db and schema names

- docker/db.py
- docker/pgosm_flex.py
- docker/qgis_styles.py
> Remove `--schema-name` option

- docs/README.md
- docs/book.toml
- docs/src/SUMMARY.md
- docs/src/docker-build.md
- docs/src/layers.md
- docs/src/layersets.md
- docs/src/replication.md
- docs/src/troubleshooting.md
Add details about layers to docs.  Tried capturing rough details about which tags are important for each layer's processing.
Updating tagged versions in docs to update with variable
> Document Logic behind layers

- docker/helpers.py
- docker/pgosm_flex.py
- docker/tests/test_geofabrik.py
- docker/tests/test_pgosm_flex.py
Follow up to #312.
The UUID was still being set as env vars and being tested.  Hasn't done anything since #312, removing.
> Finish removing UUID components

- Dockerfile
- db/deploy/replication_functions.sql
- flex-config/sql/amenity.sql
- flex-config/sql/building.sql
- flex-config/sql/building_combined_point.sql
- flex-config/sql/poi_combined_point.sql
- flex-config/sql/public_transport.sql
- flex-config/sql/shop.sql
- flex-config/sql/shop_combined_point.sql
Remove refresh of MV that no longer exists. Make comments on new tables more consistent.  Fill in missing comments.
Install PgDD extension in Docker image.  Makes `CREATE EXTENSION pgdd;` available, helpful when looking through comments on database objects.
> Cleanup RE #320

- db/data-migration/0.9.0.sql
This migration should be ran post-import with the new version.  The call to refresh the MV will exist until after 0.9.0 completes.
> Add migration script for 0.9.0 changes

- docs/src/layersets.md
Update layerset docs after changes from `_all` views to `_combined` tables in #341.
> Improve layerset docs

- docker/pgosm_flex.py
- docker/tests/layersets/place_false.ini
- docker/tests/layersets/place_missing.ini
- docker/tests/layersets/place_true.ini
- docker/tests/test_pgosm_flex.py
Addresses #347.
Fix logic related to skipping nested place polygon function when `place=false` in the layerset INI.  The problem was the value from the ini file was being returned as a `str`, while the logic was expecting a `bool`.  This moves the value parsing logic into a new function explicitly to return the boolean value, and adds unit tests to verify functionality.
With this change, it establishes that the case insensitive `true` is interpreted as `True`, everything else is `False`.
This commit is currently available as the `dev` image.
```bash
docker pull rustprooflabs/pgosm-flex:dev
```
> Fix nested polygon logic when place=false

- docs/src/custom-indexes.md
> Minor doc improvements

- .github/workflows/deploy-book.yml
- docs/README.md
- docs/book.toml
Set mdbook and mdbook-variables to install fixed versions to avoid deploy error.
https://github.com/rustprooflabs/pgosm-flex/actions/runs/5693129167
Saw reference to [this change in PL/Rust](https://github.com/tcdi/plrust/pull/360), pinned versions to match what I have installed locally.
> Fix mdbook deploy error - set fixed versions

- .github/workflows/deploy-book.yml
- docker/db.py
- docker/geofabrik.py
- docker/helpers.py
- docker/import_mode.py
- docker/osm2pgsql_recommendation.py
- docker/pgosm_flex.py
- docs/src/docker-build.md
- docs/src/replication.md
- docs/src/troubleshooting.md
Improve docblocks and type hinting.  Typo fixes.
Removed mdbook-variables.  After fiddling with it a few weeks ago (#352) to avoid failures, it was broken again (https://github.com/rustprooflabs/pgosm-flex/actions/runs/5907680184).  It wasn't worth the hassle to have a tiny number of versions injected to the docs, those can by fixed manually when they matter :shrug:
> Cleanup docblock, type hinting, remove mdbook-variables

- db/deploy/osm_pgosm_flex.sql
- docker/db.py
- docker/pgosm_flex.py
Add `input_file` column to `pgosm_flex` table to track detail when used.  Improves comment on `region` column.
> Track `--input-file` when used

- flex-config/sql/building.sql
> Fix hint of where to look for address_only_building logic

- .gitignore
- docker/db.py
- docker/helpers.py
- docker/import_mode.py
- docker/tests/test_import_mode.py
- requirements.txt
Closes #343.
When there is not a prior import tracked in `osm.pgosm_flex`, there is no change to output/operation.  When using `--replication` after the initial run, details of the prior import version will be displayed.  Same version:
```
2023-11-22 15:00:09,524:INFO:pgosm-flex:import_mode:Prior import used PgOSM Flex: 0.10.2
2023-11-22 15:00:10,580:INFO:pgosm-flex:helpers:PgOSM Flex version:  0.10.2-822ddd3
```
Example when PgOSM Flex used now is newer than prior.
```
2023-11-22 15:07:24,999:INFO:pgosm-flex:import_mode:Prior import used PgOSM Flex: 0.10.1
2023-11-22 15:07:25,020:INFO:pgosm-flex:helpers:PgOSM Flex version:  0.10.2-822ddd3
```
If the version used for prior import was newer, informs the user and stops.
```
2023-11-22 15:00:43,324:ERROR:pgosm-flex:import_mode:PgOSM Flex …
```
> Add check against prior PgOSM Flex version with replication

- LICENSE
- docs/src/quick-start.md
Improvements from review with Julie.
> Improvement to docs, license update

- Dockerfile
- docker/pgosm_flex.py
This PR started by testing https://github.com/osm2pgsql-dev/osm2pgsql/pull/2134.  Those results were encouraging and is now this is a PR addressing a couple other minor improvements.  
* Uses latest osm2pgsql, significantly reducing connection volume to Postgres https://github.com/osm2pgsql-dev/osm2pgsql/pull/2134
* Remove extra `-d` from `osm2pgsql-replication` - required to work with https://github.com/osm2pgsql-dev/osm2pgsql/pull/2115 
* Add `OSM2PGSQL_REPO` to Dockerfile for easier testing
* Adjust GitHub URL for change to `/osm2pgsql-dev/` (from `/openstreetmap/`
> Testing osm2pgsql PR #2134 for reducing conections

- docker/db.py
- docker/tests/test_db.py
Addresses #383, tests based on #384.
This approach uses `urllib.prase.quote()` to handle special characters in Postgres passwords and other conn string components.  This allows continuing to use URI style connection strings. There are a variety of places throughout the code that expect URI style connections.
The `quote()` method appears to handle the requirements defined by Postgres.
> "The connection URI needs to be encoded with [percent-encoding](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1) if it includes symbols with special meaning in any of its parts. Here is an example where the equal sign (=) is replaced with %3D and the space character with %20:"
>    From  [Postgres libpq connection docs](https://www.postgresql.org/docs/current/libpq-connect.html)
Thank you @jmealo …
> Allow special characters in DB connection parts

- docs/book.toml
- docs/src/SUMMARY.md
- docs/src/common-customization.md
- docs/src/customizations.md
- docs/src/data-files.md
Helps explain current behavior RE #385.  Creates dedicated section for data file handling.  The `--input-file` details moved to the next section along with some initial notes on `--pgosm-date`.
> Improve Docs with `--pgosm-date` details and behavior

- docker/geofabrik.py
- docker/helpers.py
- docker/pgosm_flex.py
Closes #391.
```
2024-07-06 08:22:26,658:INFO:pgosm-flex:helpers:2024-07-06 08:22:26 [INFO]: Using replication service 'http://download.geofabrik.de/north-america/us/district-of-columbia-updates'.
2024-07-06 08:22:27,940:INFO:pgosm-flex:helpers:2024-07-06 08:22:27 [ERROR]: Error during diff download. Bailing out.
2024-07-06 08:22:27,940:ERROR:pgosm-flex:helpers:Data in database is too far behind replication service.
2024-07-06 08:22:27,965:WARNING:pgosm-flex:pgosm_flex:Failure. Return code: 999
2024-07-06 08:22:27,994:WARNING:pgosm-flex:pgosm_flex:PgOSM Flex completed with errors. Details in output
PgOSM Flex completed with errors. Details in output
```
```
imported                     |osm_date  |pgosm_flex_version|import_status| …
```
> Fix uncaught error when data too old for replication update

- docker/pgosm_flex.py
- docs/src/replication.md
Prevent using `--replication` and `--force` when existing replication data exists. Add docs on how to work around for `dev` purposes.  Trying to use this on a old, messy dev server made things confusing for me a bit so failing the run and providing link to new documentation on what to do.
> Handle Replication/Force combination

- Dockerfile
- Makefile
- docs/src/docker-build.md
- docs/src/replication.md
Following https://github.com/osm2pgsql-dev/osm2pgsql/pull/2212, RE #392.
Add related documentation for how to do this testing, and that replication is not being tested by the makefile. 
Removes test broken by `osm2pgsql` #2212. The removed test only validated the initial setup of replication, not more complicated bits. `osm2pgsql` now raises an error when the file is too old (because it can't possibly update from it), which is a good thing.
If someone in the future wants to suggest an effective approach to testing the replication functionality, feel free submit an issue or PR!
> Adjust for changes to osm2pgsql RE replication initialization

- Dockerfile
I was able to upgrade the extensions packaged in this Docker image to support Postgres 17 (see [PgDD 0.6.0](https://github.com/rustprooflabs/pgdd/releases/tag/0.6.0) and [Convert 0.0.4](https://github.com/rustprooflabs/convert/releases/tag/0.0.4)). 
After I got those in place, it seems trivial to switch this project over to Postgres 17.
Test output reports zero issues.
```bash
.
----------------------------------------------------------------------
Ran 49 tests in 2.060s
OK
docker exec -it \
-e POSTGRES_PASSWORD=mysecretpassword \
-e POSTGRES_USER=postgres \
-u 1000:1000 \
pgosm /bin/bash -c "cd docker && coverage report -m ./*.py"
Name                            Stmts   Miss  Cover   Missing
-------------------------------------------------------------
./db.py …
```
> Upgrade from Postgres 16 to Postgres 17
