rustprooflabs/pgosm-flex

- README.md
- flex-config/all_tags.lua
- flex-config/building.lua
- flex-config/helpers.lua
- flex-config/indoor.lua
- flex-config/infrastructure.lua
- flex-config/natural.lua
- flex-config/place.lua
- flex-config/road.lua
- flex-config/road_major.lua
- flex-config/shop.lua
- flex-config/traffic.lua
- flex-config/unitable.lua
- flex-config/water.lua
> Make SRID and schema name configurable via env vars.

- README.md
- db/qc/features_not_in_run_all.sql
Resolves #21 
Found plenty of omissions to work through adding.
> Qc query missing features

- README.md
- flex-config/pgosm-meta.lua
- flex-config/pgosm-meta.sql
- flex-config/run-no-tags.lua
- flex-config/run-no-tags.sql
> Track PgOSM-Flex metadata in table created by processing 

- flex-config/amenity.lua
- flex-config/building.lua
- flex-config/helpers.lua
- flex-config/indoor.lua
- flex-config/infrastructure.lua
- flex-config/landuse.lua
- flex-config/leisure.lua
- flex-config/natural.lua
- flex-config/place.lua
- flex-config/road.lua
- flex-config/road_major.lua
- flex-config/shop.lua
- flex-config/water.lua
> Name improvements with helper function

- flex-config/place.sql
Progresses #37.  Needs further testing but worth integrating now.
> Nested admin poly

- flex-config/pgosm-meta.lua
* makes pgosm-flex versions automatic
* Add osm2pgsql version
> Improve meta

- Dockerfile
- flex-config/amenity.sql
- flex-config/building.sql
- flex-config/indoor.sql
- flex-config/infrastructure.sql
- flex-config/landuse.sql
- flex-config/leisure.sql
- flex-config/natural.sql
- flex-config/pgosm-meta.sql
- flex-config/place.sql
- flex-config/road.sql
- flex-config/road_major.sql
- flex-config/shop.sql
- flex-config/traffic.sql
- flex-config/unitable.sql
- flex-config/water.sql
Comment improvements.
Also has an unrelated Docker improvement I missed getting committed last night.
> Comments contd

- CONTRIBUTING.md
- DOCKER-BUILD.md
- LOAD-DATA.md
- QUERY.md
- README.md
Splitting content out of single big README into smaller, more logical components.  Improving examples and adding claritiy.
> Improve docs

- flex-config/helpers.lua
- flex-config/place.lua
- flex-config/place.sql
> Place improvements

- QUERY.md
- flex-config/helpers.lua
- flex-config/road.lua
- flex-config/road.sql
> Add methods of travel to roads

- flex-config/run-road-place.lua
- flex-config/run-road-place.sql
> Create run option to load roads, places and meta

- PERFORMANCE.md
> Performance notes

- flex-config/sql/place.sql
> Improve nested places

- LOAD-DATA.md
- README.md
- docker/run_pgosm_flex.sh
- flex-config/helpers.lua
- flex-config/sql/place.sql
- flex-config/sql/road.sql
- flex-config/style/place.lua
- flex-config/style/road.lua
Adding run time customization.
Closes #76 
Progresses #77
> Customization - Docker and Region

- README.md
- docker/run_pgosm_flex.sh
- flex-config/sql/pgosm-meta.sql
- flex-config/sql/place.sql
- flex-config/sql/road.sql
- flex-config/style/pgosm-meta.lua
- flex-config/style/place.lua
- flex-config/style/road.lua
> Move region to meta table

- flex-config/sql/building.sql
This matches what was done in `shop.sql`
> Move address calculation from view to generated column

- Dockerfile
- README.md
- flex-config/sql/amenity.sql
- flex-config/sql/building.sql
- flex-config/sql/shop.sql
- flex-config/style/shop.lua
Improving shop layer with additional amenities I expect in there.  Adds overlap to amenity layer, I'm perfectly OK with that.
Update README to start documenting prereqs.  Progresses #81,.
Update README -- document nested place polygons.
Add address generated column to amenity layer.
Add address comments to multiple layers.
> General improvements

- DOCKER-RUN.md
- MANUAL-STEPS-RUN.md
- README.md
- docker/run_pgosm_flex.sh
> Docker script - Manage dates, archives, and historic load

- README.md
- docker/run_pgosm_flex.sh
> Docker script - Check for Postgres service available

- DOCKER-RUN.md
- docker/run_pgosm_flex.sh
> Docker script - default to calculate nested polygons

- DOCKER-RUN.md
- README.md
- flex-config/helpers.lua
- flex-config/style/place.lua
> Add language priority to `get_name()`

- Dockerfile
- MANUAL-STEPS-RUN.md
- README.md
- flex-config/rxi-json.lua
- flex-config/style/place.lua
- flex-config/style/tags.lua
- flex-config/style/unitable.lua
> Replace dkjson with rxi-json.lua

- .github/workflows/docker-build.yml
> Docker actions

- db/qc/features_not_in_run_all.sql
- flex-config/helpers.lua
- flex-config/sql/amenity.sql
- flex-config/sql/building.sql
- flex-config/sql/poi.sql
- flex-config/sql/shop.sql
- flex-config/style/amenity.lua
- flex-config/style/building.lua
- flex-config/style/poi.lua
- flex-config/style/shop.lua
> Add postcode

- flex-config/style/poi.lua
Started looking at #105 and found a couple other improvements to make.
* Add historic tags (#105)
* Add relations
* remove buildings with no name (empty string)
> Improve POIs

- PERFORMANCE.md
- db/qc/features_not_in_run_all.sql
- flex-config/style/amenity.lua
- flex-config/style/building.lua
- flex-config/style/poi.lua
Closes #109.
Added relation handling to `building.lua`.  `amenity.lua` had the relations, that case was the QC queries were not removing them from the list of missing.
> Relation improvements

- docker/run_pgosm_flex.sh
Closes #135 and #131.
* Allows setting subregion to `None` to download parent region, e.g. North America
* Output `.sql` filename combines region & subregion instead of simply subregion
> Improve Docker run RE region/sub-region

- flex-config/helpers.lua
- flex-config/sql/public_transport.sql
- flex-config/sql/road.sql
- flex-config/sql/road_major.sql
- flex-config/style/public_transport.lua
- flex-config/style/road.lua
- flex-config/style/road_major.lua
> Improve ref

- flex-config/sql/pgosm-meta.sql
- flex-config/style/pgosm-meta.lua
> Track language in osm.pgosm_flex table 

- DOCKER-RUN.md
- docker/pgosm_flex.py
> Add --skip-dump option

- docker/pgosm_flex.py
> File handling  improvements

- docker/pgosm_flex.py
> Set `PGOSM_DATE` env var

- docs/ROUTING.md
Add `oneway` routing example showing usage of values. #172
> Update routing example

- README.md
- docs/DOCKER-RUN.md
- docs/MANUAL-STEPS-RUN.md
- flex-config/sql/poi.sql
Quick review of readme files, a variety of updates.  Cleaning out some outdated instructions, adding new examples, etc.
Noticed a column missing a comment, added that too.
> Docs and comments

- docker/osm2pgsql_recommendation.py
- requirements.txt
Closes #187.
Starts the ball rolling on #193.
> Switch osm2pgsql recommendation from api call to import package. 

- docker/pgosm_flex.py
Rearrange click options putting required & common options first. Remainder are in alphabetical order. Improve help messages, set data type for RAM.
The RAM type decided to pass along an integer when I removed the default value of 4 (odd).  Set `type=float` to resolve.
> Cleanup click options

- Makefile
- docker/db.py
- docker/osm2pgsql_recommendation.py
- docker/pgosm_flex.py
- docs/DOCKER-RUN.md
Merging a few recent changes.
New feature
* Add option to specify explicit file - #192
Bug fixes
* Resolves #197
* Resolves #198
* Resolves #199
Docs
* Reorder/improve click options #204
> File handling, input validity, documentation

- docker/db.py
- docker/geofabrik.py
- docker/helpers.py
- docker/osm2pgsql_recommendation.py
- docker/pgosm_flex.py
- docker/tests/test_db.py
- docker/tests/test_geofabrik.py
- docker/tests/test_helpers.py
- docker/tests/test_osm2pgsql_recommendation.py
Merging changes from #207 and #208 into main branch.  No functional changes.  Continues addressing #193 and setting the stage for #194.
> Cleanup code and add tests

- flex-config/sql/road.sql
> Add missing comment on osm.road_polygon.ref 

- Makefile
- docker/db.py
- docker/pgosm_flex.py
- docker/tests/test_pgosm_flex.py
- flex-config/sql/pgosm-meta.sql
- flex-config/sql/road.sql
- flex-config/style/pgosm-meta.lua
- tests/run-output-tests.sh
Merge recent changes into `main` from `dev`.
* Add `osm2pgsql_mode` (create/append) to `osm.pgosm_flex` #212
* Add missing comment #210
* Update `.sql` output name to include date with `--input-file` - #214 
* Makefile & testing improvements - #214
> Cleanup, osm2pgsql_mode, tests and minor bug

- docs/MANUAL-STEPS-RUN.md
Add troubleshooting section to manual steps docs. Addresses #218 and generic osm2pgsql troubleshooting.
> Add troubleshooting section to manual steps readme

- flex-config/style/infrastructure.lua
- tests/expected/infrastructure_line_osm_type_subtype_count.out
- tests/expected/infrastructure_point_osm_type_subtype_count.out
- tests/expected/infrastructure_polygon_osm_type_subtype_count.out
> Fix aeroway

- docker/db.py
- docker/helpers.py
- docker/osm2pgsql_recommendation.py
Change some logs to debug from info and simplify a message.
> Reduce log output

- docs/MANUAL-STEPS-RUN.md
Add link to new max connections section in osm2pgsql docs. See #226 and https://github.com/openstreetmap/osm2pgsql/discussions/1650 for context
> Add troubleshooting notes and link to docs about too many connections.

- docker/pgosm_flex.py
> Add deprecation warning to --basepath

- Dockerfile
- flex-config/sql/amenity.sql
- flex-config/style/amenity.lua
* Add `osm_subtype` column to `amenity` layer tables (point/line/polygon)
* Set `osm_subtype` for `amenity=shelter`  -- Starts improving for  #239 
* Set `osm_subtype` for food related amenities
> Add subtype to amenity layer

- flex-config/style/building.lua
- tests/expected/vbuilding_all_osm_type_subtype_count.out
> Exclude additional tags from address-only buildings

- docker/db.py
- docs/DOCKER-RUN.md
- flex-config/style/building.lua
- flex-config/style/infrastructure.lua
- tests/expected/infrastructure_line_osm_type_subtype_count.out
- tests/expected/infrastructure_point_osm_type_subtype_count.out
- tests/expected/infrastructure_polygon_osm_type_subtype_count.out
- tests/expected/vbuilding_all_osm_type_subtype_count.out
Merge work from #245, #246, and #247
> Merge development into main

- docker/README.md
- docker/pgosm_flex.py
- docker/tests/test_db.py
- docker/tests/test_osm2pgsql_recommendation.py
- docker/tests/test_pgosm_flex.py
- docs/DOCKER-RUN.md
> Remove basepath

- flex-config/style/road_major.lua
> Remove columns that do not exist from road_major

- Dockerfile
The main change is to update to Postgres 15.  To get the latest image to work I had to add `USE_PROJ_LIB = 6`, for some reason the default `auto` setting was failing.
Also updated:
* Lua from 5.2 -> 5.4
* luarocks from 3.8.0 -> 3.9.1
> Update Docker image for Postgres 15

- docker/helpers.py
Broke in #273, hadn't noticed this in the make testing output earlier.
> Fixes hard failure when md5sum check fails

- docker/pgosm_flex.py
- docs/DOCKER-RUN.md
> Fix reported osm_date when osm2pgsql-replication updates data

- docker/db.py
- docker/helpers.py
- docker/pgosm_flex.py
- flex-config/sql/pgosm-meta.sql
- flex-config/style/pgosm-meta.lua
> Add ability to track import errors in osm.pgosm_flex table

- flex-config/sql/pgosm-meta.sql
- flex-config/style/pgosm-meta.lua
> Remove project_url column

- docs/src/readme.md
Add links to production usage pages RE external connections and replication
> Minor documentation improvement

- docs/src/SUMMARY.md
- docs/src/projects.md
Add Geo Faker to projects list.  Add projects listing to docs navigation
> Add Geo Faker to projects 

- Dockerfile
> Remove apt upgrade -y step from Dockerfile

- docker/db.py
> Adding function to log Postgres connection details

- Dockerfile
> Install nlohmann-json3-dev for latest osm2pgsql

- Dockerfile
> Update to use Postgres 16 in Docker image

- flex-config/style/tags.lua
> Change add_row to insert

- Dockerfile
- docs/src/docker-build.md
Added build to create installer for this in https://github.com/rustprooflabs/convert/pull/7
> Add convert extension into build. Update docker docs

- docs/src/quick-start.md
Var was set but not passed to container. Technically worked, but...
> Minor fix in quick start

- docker/helpers.py
> Remove PGOSM_REPLICATION env var

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE/pull_request.md
- docs/src/code-of-conduct.md
- docs/src/contributing.md
Reworks contributing guidelines to provide better guidance for interacting with this project, per discussions with Julie.
Add PR template. Minor adjustment to Bug report template.
> Contributing Guidelines
